hydra:
  output_subdir: null
  run:
    dir: .

defaults:
  - process: process1
  - model: model1
  - _self_

data:
  imported: data/imported/imported.csv
  raw: data/raw/sample.csv
  staging: data/staging/staging.csv
  clean: data/clean/clean.csv
